export const SET_USERS_FOR_COUNTRY_STARTED = "SET_USERS_FOR_COUNTRY_STARTED";
export const SET_USERS_FOR_COUNTRY_SUCCESS = "SET_USERS_FOR_COUNTRY_SUCCESS";
export const SET_USERS_FOR_COUNTRY_ERROR = "SET_USERS_FOR_COUNTRY_ERROR";
export const GET_USERS_FOR_COUNTRY_STARTED = "GET_USERS_FOR_COUNTRY_STARTED";
export const GET_USERS_FOR_COUNTRY_SUCCESS = "GET_USERS_FOR_COUNTRY_SUCCESS";
export const GET_USERS_FOR_COUNTRY_ERROR = "GET_USERS_FOR_COUNTRY_ERROR";
export const PAGE_CHANGE = "PAGE_CHANGE";
